---
output: pdf_document
---

```{r}
install.packages("plotly")
library(shiny)
library(datasets)
library(ggplot2)
library(dplyr)
library(plotly)
require(lubridate)
library(dygraphs)
library(xts)

A <- readRDS("~/Desktop/ONE.Rds")
FIVE <- readRDS("~/Desktop/FIVE.Rds")
THREE <- readRDS("~/Desktop/THREE.Rds")

C <- data.frame(Borough = A$Borough[A$Status == "Closed"], Complaint.Type = A$Complaint.Type[A$Status == "Closed"],Days = A$Days[A$Status == "Closed"])

```

#pie chart
```{r}
plot_ly(A, values = c(length(A$Status[A$Status == "Open"]),length(A$Status[A$Status == "Closed"])), labels=c("Open","Closed"), type="pie")

#
summary(A$Borough[A$Status == "Open"])
Borough <- data.frame(summary(A$Borough[A$Status == "Open"]))
value <- c(Borough[,1])
name <- c(rownames(Borough))
plot_ly(values = value, labels = c(name),type="pie")

# open 
summary(A$Complaint.Type[A$Status == "Open"])
Type <- data.frame(summary(A$Complaint.Type[A$Status == "Open"]))
value <- c(Type[,1])
name <- c(rownames(Type))
plot_ly(A, values = value, labels = c(name),type="pie", showlegend = F) %>% layout(title = "Open cases by Complaint.Type") 
```

#Timeline
```{r}
ALL <- data.frame(table(A$Date))
ALL$Var1 <- as.POSIXct(ALL$Var1)
ALL <- xts(ALL[,-1], order.by=ALL[,1])
ALL <- xts(ALL[,-1], order.by=ALL[,1])

MANHATTAN <- data.frame(table(A$Date[A$Borough == "MANHATTAN"]))
MANHATTAN$Var1 <- as.POSIXct(MANHATTAN$Var1)
MANHATTAN <- xts(MANHATTAN[,-1], order.by = MANHATTAN[,1])

BRONX <- data.frame(table(A$Date[A$Borough == "BRONX"]))
BRONX$Var1 <- as.POSIXct(BRONX$Var1)
BRONX <- xts(BRONX[,-1], order.by = BRONX[,1])

BROOKLYN <- data.frame(table(A$Date[A$Borough == "BROOKLYN"]))
BROOKLYN$Var1 <- as.POSIXct(BROOKLYN$Var1)
BROOKLYN <- xts(BROOKLYN[,-1], order.by = BROOKLYN[,1])

QUEENS <- data.frame(table(A$Date[A$Borough == "QUEENS"]))
QUEENS$Var1 <- as.POSIXct(QUEENS$Var1)
QUEENS <- xts(QUEENS[,-1], order.by = QUEENS[,1])

STATEN_ISLAND <- data.frame(table(A$Date[A$Borough == "STATEN ISLAND"]))
STATEN_ISLAND$Var1 <- as.POSIXct(STATEN_ISLAND$Var1)
STATEN_ISLAND <- xts(STATEN_ISLAND[,-1], order.by = STATEN_ISLAND[,1])

FIVE <- cbind(ALL, BRONX, BROOKLYN, MANHATTAN, QUEENS, STATEN_ISLAND)
colnames(FIVE) <- c("ALL", "BRONX", "BROOKLYN" , "MANHATTAN" , "QUEENS", "STATEN_ISLAND")

dygraph(FIVE, main = "Numbers of Calls" ) %>% dyRangeSelector()
saveRDS(FIVE, file = "~/Desktop/FIVE.Rds")
```

#Timeline by type
```{r}
DrinkingWater <- data.frame(table(A$Date[A$Complaint.Type == "Drinking Water" | A$Complaint.Type == "Water Quality"]))
DrinkingWater$Var1 <- as.POSIXct(DrinkingWater$Var1)
DrinkingWater <- xts(DrinkingWater[,-1], order.by = DrinkingWater[,1])

HEATHOTWATER <- data.frame(table(A$Date[A$Complaint.Type == "HEAT/HOT WATER"]))
HEATHOTWATER$Var1 <- as.POSIXct(HEATHOTWATER$Var1)
HEATHOTWATER <- xts(HEATHOTWATER[,-1], order.by = HEATHOTWATER[,1])

WaterSystem <- data.frame(table(A$Date[A$Complaint.Type == "Water System"]))
WaterSystem$Var1 <- as.POSIXct(WaterSystem$Var1)
WaterSystem <- xts(WaterSystem[,-1], order.by = WaterSystem[,1])

WATERLEAK <- data.frame(table(A$Date[A$Complaint.Type == "WATER LEAK"]))
WATERLEAK$Var1 <- as.POSIXct(WATERLEAK$Var1)
WATERLEAK <- xts(WATERLEAK[,-1], order.by = WATERLEAK[,1])

THREE <- cbind(DrinkingWater, HEATHOTWATER, WaterSystem, WATERLEAK)
colnames(THREE) <- c("DrinkingWater", "Heat/Hot.Water", "WaterSystem", "WaterLeak")

dygraph(THREE, main = "Numbers of Calls" ) %>% dyRangeSelector()
saveRDS(THREE, file = "~/Desktop/THREE.Rds")
```


#Average solving time on closed cases by borough
```{r}
a <- list(
  range = c(-5,15)
)

plot_ly(C, x = Borough, y = Days, color = Borough, type = "box", boxmean = T) %>% layout(yaxis = a)

```

#solving time by Complaint.Type
```{r}
a <- list(
  range = c(-5,60)
)

plot_ly(C, x = Complaint.Type, y = Days, color = Complaint.Type, type = "box", boxmean = T) %>% layout(yaxis = a)
```

```{r}
a <- list(
  range = c(-5,60)
)

plot_ly(C,x = Borough, y = Days, color = Complaint.Type, type = "box", boxmean = T) %>% layout(boxmode = "group", yaxis = a)

```


```{r}
summary <- data.frame(tapply(A$Days, list(A$Complaint.Type, A$Borough), mean, na.rm=TRUE))


summary1 <- data.frame(aggregate(A$Days[A$Status == "Closed"], by = list(A$Borough[A$Status == "Closed"]), mean, na.rm = T))
names(summary1) <- c("Borough", "Average")

summary2 <- data.frame(aggregate(A$Days[A$Status == "Closed"], by=list(A$Complaint.Type[A$Status == "Closed"]), mean, na.rm = T))
names(summary2) <- c("Complaint.Type", "Average")

summary <- data.frame(tapply(A$Days[A$Status == "Closed"], list(A$Complaint.Type[A$Status == "Closed"], A$Borough[A$Status == "Closed"]), mean, na.rm=TRUE))

```


```{r}
library(leaflet)
A <- readRDS("~/Desktop/ONE.Rds")
FIVE <- readRDS("~/Desktop/FIVE.Rds")
THREE <- readRDS("~/Desktop/THREE.Rds")

 leaflet(na.omit(A)) %>% addTiles() %>% addProviderTiles("CartoDB.Positron") %>% setView(lng = -73.9857, lat = 40.7577, zoom = 12) %>% addCircleMarkers(radius=6, fillOpacity = 0.5, popup = paste(A$Days),color = paste(A$Complaint.Type), clusterOptions = markerClusterOptions())
```

