---
output: pdf_document
---

#clean data part 1:
```{r}
#remove space between variable names
D1 <-transform(D1,dymmyvar = 1)
D1$dymmyvar <- NULL
D1 <- D1[,-c(3,11:14,17,19)]

#Complaint.Type
D1$Complaint.Type <- as.factor(D1$Complaint.Type)
levels(D1$Complaint.Type)

#Cities
D1$City <- as.factor(toupper(as.character(D1$City)))
levels(D1$City)

#Borough
D1$Borough <- as.factor(D1$Borough)
levels(D1$Borough)

#change format of date and time
D1$Created.Date <- strptime(D1$Created.Date, "%m/%d/%Y %I:%M:%S %p")

#change date/time format and Split date and time 
D1$Date <- sapply(strsplit(as.character(D1$Created.Date), " "), "[", 1)
D1$Time <- sapply(strsplit(as.character(D1$Created.Date), " "), "[", 2)

DATE1 <- as.Date("2013-01-01")
DATE2 <- as.Date("2015-12-31")
new_data <- D1[D1$Date >= DATE1 & D1$Date <= DATE2,]
saveRDS(new_data, file="data_3.Rds")

D2 <- readRDS("~/Desktop/data_3.rds")
D1 <- D1[,-c(1,3,10)]
D1$Resolution.Action.Updated.Date <- strptime(D1$Resolution.Action.Updated.Date, "%m/%d/%Y %I:%M:%S %p")
D1$Updated_Date <- sapply(strsplit(as.character(D1$Resolution.Action.Updated.Date), " "), "[", 1)
D1$Updated_Time <- sapply(strsplit(as.character(D1$Resolution.Action.Updated.Date), " "), "[", 2)

D1 <- readRDS("~/Desktop/data_4.rds")
```

#clean data part 2:
#Resouluton time
```{r}
D1 <- readRDS("~/Desktop/data_4.rds")
A <- data.frame(c(D1[,c(1,2,8:10,11:13,15:18)]))
A$Days <- round(difftime(A$Resolution.Action.Updated.Date, A$Created.Date, units = "days"),0)
A$Days <- as.numeric(A$Days)
saveRDS(A, file = "~/Desktop/ONE.Rds")
```

